eigerco/strawberry

internal/polkavm/host_call/accumulate_functions.go
internal/polkavm/host_call/accumulate_functions_test.go
internal/polkavm/host_call/common.go
internal/polkavm/host_call/general_functions.go
internal/polkavm/host_call/general_functions_test.go
internal/statetransition/accumulate.go
internal/statetransition/on_transfer.go
pkg/serialization/codec/jam/decode.go
pkg/serialization/codec/jam/encode.go
pkg/serialization/codec/jam/general_natural.go
pkg/serialization/codec/jam/general_natural_test.go
pkg/serialization/codec/jam/trivial_natural.go
pkg/serialization/codec/jam/trivial_natural_test.go

I updated the accumulate and general host functions to align with the 0.5.0 changes. The transition of registers and host result codes to `uint64` will be addressed in a separate PR.

Update PVM host functions to 0.5.0

---

pkg/network/cert/cert.go
pkg/network/cert/cert_test.go

This is just a generate/validate self signed cert.
The relevant part from the https://github.com/zdave-parity/jam-np/blob/main/simple.md:
```During the TLS handshake, both the client (the peer that initiated the connection) and the server (the peer that accepted the connection) must present X.509 certificates. A peer's certificate must:
Use Ed25519 as the signature algorithm.
Use the peer's Ed25519 key. If the peer is a validator, this key should have been published on chain.
Have a single alternative name, which must be a 53-character DNS name consisting of "e" followed by the Ed25519 public key, base-32 encoded using the alphabet "abcdefghijklmnopqrstuvwxyz234567".
The certificates should be self-signed, however this is not required and need not be verified.

Add certificate generation and validation

---

pkg/network/transport/protocol/alpn.go
pkg/network/transport/protocol/alpn_test.go

```The protocol name, version, and chain are identified using QUIC/TLS "ALPN" (Application Layer Protocol Negotiation). The (ASCII-encoded) protocol identifier should be either jamnp-s/V/H or jamnp-s/V/H/builder. Here V is the protocol version, 0, and H is the first 8 nibbles of the hash of the chain's genesis header, in lower-case hexadecimal.```

Add alpn protocol ID

---

internal/polkavm/host_call/common.go
internal/polkavm/host_call/refine_functions.go
internal/polkavm/host_call/refine_functions_test.go

Add import host function

---

internal/block/block.go
internal/block/header.go
internal/store/chain.go
internal/store/chain_test.go

This PR adds the functionality to store blocks. 
For `GetBlockSequence`, we have this info from the `CE 128: Block request`:
```
Ascending exclusive: The sequence of blocks in the response should start with a child of the given block, 
followed by a grandchild, and so on.
Descending inclusive: The sequence of blocks in the response should start with the given block, 
followed by its parent, grandparent, and so on.
```
Closes https://github.com/eigerco/strawberry/issues/206

Add block store

---

internal/polkavm/interpreter/mutator.go
pkg/serialization/codec/jam/common.go
pkg/serialization/codec/jam/decode.go
pkg/serialization/codec/jam/encode.go
pkg/serialization/codec/jam/encode_decode_jam_test.go
pkg/serialization/codec/jam/errors.go
pkg/serialization/codec/jam/trivial_natural.go
pkg/serialization/codec/jam/trivial_natural_test.go

Closes https://github.com/eigerco/strawberry/issues/225

Support fixed-length encoding for integers in JAM codec

---

internal/validator/grid.go
internal/validator/grid_test.go

Closes https://github.com/eigerco/strawberry/issues/230
```
Primarily for the purpose of block announcements, the previous, current, 
and next validator sets are conceptually arranged in a grid structure. 
Two validators are considered neighbours in the grid if:
They are validators in the same epoch and either have the same row (index / W) 
or the same column (index % W). W here is floor(sqrt(V)), where V is the number of validators.
They are validators in different epochs but have the same index.
```

Add validator grid mapper for neighbor discovery

---

internal/statetransition/state_transition.go
tests/integration/reports_test.go

After checking with davxy in matrix, it seems the check was unneeded for STF test vectors, that's why they remained unchanged although they should have been modified on the post state.
Closes: https://github.com/eigerco/strawberry/issues/223

Reports test vectors should not check authorizations

---

internal/state/block_seal.go
internal/state/block_seal_test.go
internal/testutils/utils.go
tests/integration/sealing_test.go

- Fix block sealing. We should have included the VRF signature before sealing.
- Add a function to verify block signatures.
- Add community test vector integration tests. (These were somehow left out of the past commit)
- Misc renaming for clarity.

Update block sealing

---

pkg/network/handlers/testutils/mock_stream.go
pkg/network/handlers/work_package_submission.go
pkg/network/handlers/work_package_submission_test.go
pkg/network/peer/node.go

Partial implementation of CE-133 (since the availability system is not in place we cannot fetch the import segments yet)
Part of this https://github.com/eigerco/strawberry/issues/156

CE 133 Work package submission

---

internal/crypto/bandersnatch/bandersnatch.go
internal/safrole/state.go
internal/state/block_seal.go
internal/state/ticket.go
internal/state/ticket_test.go
internal/statetransition/state_transition.go
tests/simulation/simulation_test.go

Also:
- Add functions to Create and Verify ticket proofs.
- Add method to get a RingProver from the SAFROLE state. Used to generate ring signatures for ticket proof submission.
- Rearrange SAFROLE state transition code given issues found during simulation. The accumulator needed to be reset before new tickets are added.
Closes #285

Add SAFROLE ticket simulation

---

internal/common/constants.go
internal/common/constants_integration.go
internal/erasurecoding/erasurecoding.go

- Add integration (tiny) constants.
- Add no original shards constant.
- Fix the erasure coding chunk size and number of erasure codec pieces as constants in line with GP values.

Update erasure coding constants

---

internal/state/merkle/helpers_test.go
internal/state/merkle/serialization.go
internal/state/state.go
internal/statetransition/state_transition.go
internal/statetransition/state_transition_test.go
internal/validator/validators.go
tests/integration/statistics_test.go

Add initial ActivityStatistics structs which replace ValidatorStatistics.
The primary purpose of this commit is to add enough of ActivityStatistics to allow work on JSON encoding/decoding the state to continue which requires these structs to exist.
The logic for computing ValidatorStatistics hasn't really changed. There are no test vectors for the new core statistics and service statistics. It seemed prudent to rather wait for vectors to be available before starting work on the logic to compute them.
An attempt was made to update the test vectors to the latest despite the above, but the changes to these test vectors affect other test vectors too, and hence it makes more sense to update all the others with the same minor changes.

ValidatorStatistics -> ActivityStatistics

---

internal/store/trie.go
internal/store/trie_test.go

CE129 is a protocol that handles State requests. It allows nodes to request a range of a block's posterior state between two keys with a size limit. The protocol returns:
A series of key/value pairs from the state trie
Boundary nodes to verify the returned data
The FetchStateTrieRange function implements:
Accepting the exact parameters specified in CE129 (start key, end key, max size)
Returning key/value pairs within the specified range
Providing boundary nodes covering paths from root to start key and to the last returned key
Enforcing size limits as required by the protocol
This is data part of https://github.com/eigerco/strawberry/issues/229. After this is merged, the last PR would be to request and send that data.

Add fetch state trie range

---

internal/testutils/json/json.go
tests/simulation/simulation_test.go

Modify the simulation test to use the full UpdateState function.
Also:
- Use json test utils to restore the state.
- Fix  restoring sealing keys in json utils.

Use UpdateState for simulation test

---

pkg/network/network_test.go
pkg/network/node/node.go

Erasure coded shards are assigned to validators as follows:
```math
i = (cR + v) \bmod V
```
Where:
- $v$ is the index of a validator.
- $i$ is the index of the shard assigned to the validator.
- $c$ is the index of the core which produced the work-report.
- $R$ is the recovery threshold: the minimum number of EC shards required to recover the original
data. With 1023 validators, $R = 342$.
- $V$ is the number of validators.

Shard assignment

---

internal/state/merkle/helpers_test.go
internal/state/merkle/serialization.go
internal/state/merkle/serialization_test.go
internal/state/merkle/serialization_utils.go
internal/state/merkle/serialization_utils_test.go
internal/state/types.go

State serialization as per GP 0.6.6 switched from 32 -> 31 byte state keys. This commit adds a StateKey type of [31]byte and updates the state serialisation to use it.
This change doesn't change much practically since the last byte was unused anyway.
Also some small refactors for clarity.

Update state serialization to use a 31 byte state key

---

internal/store/trie_test.go
pkg/network/handlers/state_request.go
pkg/network/network_test.go
pkg/network/node/node.go

Adds a state request network protocol CE129. This is closing https://github.com/eigerco/strawberry/issues/229 and https://github.com/eigerco/strawberry/issues/164.
```Key = [u8; 31] (First 31 bytes of key only)
Maximum Size = u32
Boundary Node = As returned by B/L, defined in the State Merklization appendix of the GP
Value = len++[u8]
Node -> Node
--> Header Hash ++ Key (Start) ++ Key (End) ++ Maximum Size
--> FIN
<-- [Boundary Node]
<-- [Key ++ Value]
<-- FIN
```
Added some additional tests for the trie.

Add state request

---

internal/state/merkle/deserialization.go
internal/state/merkle/serialization.go
internal/state/merkle/serialization_utils.go
internal/state/merkle/serialization_utils_test.go
tests/integration/state_serialization_test.go

- Move deserialization functions to their own file.
- Sort by the type of key before deserializing for efficiency and clarity.
- Add deserialization for preimages. This is fairly straight forward since we can just hash the preimage to get back it's key.
- Fix service serialization, total items/storage should use the functions on the service account for this and not do their own calculation.
- Fix state serialization integration test, there was a bug where we weren't checking the correct state. Also ignore the storage/items fields of the service account for now in the test since we won't get correct values for these until we're also deserializing storage keys.
- Some refactoring for clarity.

Deserialize preimages

---

internal/polkavm/program.go
internal/statetransition/accumulate.go
tests/integration/accumulate_test.go

The program blob now includes metadata first, and then the rest of the program blob. Parse this first and update our validation checks.
Also fix the accumulate test. The accumulate code is running now so a storage key is set by it. For now we need to ignore storage keys when checking state equality until we update to the v0.6.5 vectors which do contain storage keys as part of the vector's state.

Fix PVM program blob parsing

---

internal/statetransition/state_transition.go
tests/integration/assurances_test.go
tests/integration/disputes_test.go
tests/integration/vectors/disputes/tiny/progress_invalidates_avail_assignments-1.json
tests/integration/vectors/disputes/tiny/progress_with_bad_signatures-1.json
tests/integration/vectors/disputes/tiny/progress_with_bad_signatures-2.json
tests/integration/vectors/disputes/tiny/progress_with_culprits-1.json
tests/integration/vectors/disputes/tiny/progress_with_culprits-2.json
tests/integration/vectors/disputes/tiny/progress_with_culprits-3.json
tests/integration/vectors/disputes/tiny/progress_with_culprits-4.json
tests/integration/vectors/disputes/tiny/progress_with_culprits-5.json
tests/integration/vectors/disputes/tiny/progress_with_culprits-6.json
tests/integration/vectors/disputes/tiny/progress_with_culprits-7.json
tests/integration/vectors/disputes/tiny/progress_with_faults-1.json
tests/integration/vectors/disputes/tiny/progress_with_faults-2.json
tests/integration/vectors/disputes/tiny/progress_with_faults-3.json
tests/integration/vectors/disputes/tiny/progress_with_faults-4.json
tests/integration/vectors/disputes/tiny/progress_with_faults-5.json
tests/integration/vectors/disputes/tiny/progress_with_faults-6.json
tests/integration/vectors/disputes/tiny/progress_with_faults-7.json
tests/integration/vectors/disputes/tiny/progress_with_invalid_keys-1.json
tests/integration/vectors/disputes/tiny/progress_with_invalid_keys-2.json
tests/integration/vectors/disputes/tiny/progress_with_no_verdicts-1.json
tests/integration/vectors/disputes/tiny/progress_with_verdict_signatures_from_previous_set-1.json
tests/integration/vectors/disputes/tiny/progress_with_verdicts-1.json
tests/integration/vectors/disputes/tiny/progress_with_verdicts-2.json
tests/integration/vectors/disputes/tiny/progress_with_verdicts-3.json
tests/integration/vectors/disputes/tiny/progress_with_verdicts-4.json
tests/integration/vectors/disputes/tiny/progress_with_verdicts-5.json
tests/integration/vectors/disputes/tiny/progress_with_verdicts-6.json

Update disputes test vectors. 
Added check for fault or culprit if a validator. 
Added a log in case we failed to hash a work report (was silenced before).

Update disputes test vectors

---

internal/authorization/authorization.go
internal/polkavm/common.go
internal/polkavm/host_call/accumulate_functions.go
internal/polkavm/host_call/accumulate_functions_test.go
internal/polkavm/host_call/common.go
internal/polkavm/host_call/refine_functions.go
internal/polkavm/host_call/refine_functions_test.go
internal/refine/refine.go
internal/statetransition/accumulate.go
internal/statetransition/on_transfer.go
internal/statetransition/state_transition.go
tests/integration/accumulate_test.go

This PR:
- Renumbers the host call ids as defined in latest versions
- Merges Zero & Void into new Pages host call
- Adds provide host call
- Updates invocations 
- Skips accumulation test vectors for now

PVM invocation updates v0.6.7

---

internal/block/block_test.go
internal/block/dispute.go
internal/common/constants.go
internal/common/constants_integration.go
internal/disputes/disputes.go
internal/statetransition/state_transition.go
internal/testutils/json/block.go
tests/integration/codec_integration_test.go
tests/integration/disputes_test.go

Moved most of the logic out from `statetransition` into new package `disputes`. 
Added a new `VerdictSummary` to more accurately follow the GP.
Optimized verifications.
Updated equation comments.

Update disputes v0.6.7

---

internal/polkavm/host_call/accumulate_functions.go
internal/polkavm/host_call/accumulate_functions_test.go
internal/polkavm/host_call/general_functions.go
internal/polkavm/host_call/general_functions_test.go
internal/service/service.go
internal/service/service_test.go
internal/state/serialization/deserialization.go
internal/state/serialization/serialization.go
internal/state/serialization/testutils.go
internal/statetransition/accumulate.go
internal/statetransition/state_transition_test.go
internal/testutils/json/state.go
internal/work/package_test.go
tests/integration/accumulate_test.go
tests/integration/json_test.go
tests/integration/preimages_test.go
tests/integration/reports_test.go

This PR: 
- Updates the account footprint and threshold balance calculations to account for the original key size, along with other formula adjustments introduced in v0.6.7
- Modifies the read and write host calls to avoid hashing storage keys twice
- Skips a JSON test that relies on old GP version

Balance calculation updates v0.6.7

---

internal/polkavm/host_call/general_functions.go
internal/polkavm/host_call/general_functions_test.go
internal/state/serialization/deserialization.go
internal/state/serialization/statekey/statekey.go
internal/state/serialization/statekey/statekey_test.go
tests/integration/accumulate_test.go

The last airity for the state key constructor function has changed. We now do the key hashing inside this function, and the state serialisation function merely passes the data to hash.
Because of this we can no longer tell the difference between storage state keys and preimage meta keys anymore. The assumption now is that the host shouldn't need to care how the keys are stored, as long as the underlying host calls can read and write their data.
It's implied that all service dictionary keys should be stored in a single map or KV DB. Each host call would know how to access it's key and value.
So all functionality related to figuring out which type of service dictionary key a given state key is has been removed. We can no longer deserialize service dictionaries.
We will have to revisit this …

Update state keys 0.6.7

---

internal/state/block.go
internal/statetransition/state_transition.go

- Add a Clone method to RecentHistory.
- Use this to deep copy recent history during state transitions.

Deep copy recent history

---

internal/block/preimage.go
internal/statetransition/state_transition.go
internal/statetransition/state_transition_test.go
tests/integration/preimages_test.go

separate the preimage integration in two steps 
1. validating that the preimages are ordered, unique and solicited by the initial service and 
2. integrating the solicited preimages
also updates the comments to v0.7.0

fix: validate preimages using initial service state
